//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AmountHint {
            get {
                return ResourceManager.GetString("AmountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24h Change (%).
        /// </summary>
        internal static string Change24hHeader {
            get {
                return ResourceManager.GetString("Change24hHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24h Change: {0:N2}%.
        /// </summary>
        internal static string Change24hLabelFormat {
            get {
                return ResourceManager.GetString("Change24hLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string ConvertButton {
            get {
                return ResourceManager.GetString("ConvertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Currency.
        /// </summary>
        internal static string ConvertCurrencyButton {
            get {
                return ResourceManager.GetString("ConvertCurrencyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Converter.
        /// </summary>
        internal static string CurrencyConverterTitle {
            get {
                return ResourceManager.GetString("CurrencyConverterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for {0}.
        /// </summary>
        internal static string DetailsTitleFormat {
            get {
                return ResourceManager.GetString("DetailsTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        internal static string ExchangeHeader {
            get {
                return ResourceManager.GetString("ExchangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Currency.
        /// </summary>
        internal static string FromCurrencyHint {
            get {
                return ResourceManager.GetString("FromCurrencyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string GoButton {
            get {
                return ResourceManager.GetString("GoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High 24h: {0:C2}.
        /// </summary>
        internal static string High24hLabelFormat {
            get {
                return ResourceManager.GetString("High24hLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated: {0:yyyy-MM-dd HH:mm}.
        /// </summary>
        internal static string LastUpdatedLabelFormat {
            get {
                return ResourceManager.GetString("LastUpdatedLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low 24h: {0:C2}.
        /// </summary>
        internal static string Low24hLabelFormat {
            get {
                return ResourceManager.GetString("Low24hLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets:.
        /// </summary>
        internal static string MarketsLabel {
            get {
                return ResourceManager.GetString("MarketsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (USD).
        /// </summary>
        internal static string PriceHeader {
            get {
                return ResourceManager.GetString("PriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (USD): {0:C2}.
        /// </summary>
        internal static string PriceLabelFormat {
            get {
                return ResourceManager.GetString("PriceLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceMarketHeader {
            get {
                return ResourceManager.GetString("PriceMarketHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string RankHeader {
            get {
                return ResourceManager.GetString("RankHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Coins.
        /// </summary>
        internal static string SearchCoinsButton {
            get {
                return ResourceManager.GetString("SearchCoinsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter coin name or symbol....
        /// </summary>
        internal static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string SymbolHeader {
            get {
                return ResourceManager.GetString("SymbolHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol: {0}.
        /// </summary>
        internal static string SymbolLabelFormat {
            get {
                return ResourceManager.GetString("SymbolLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Currency.
        /// </summary>
        internal static string ToCurrencyHint {
            get {
                return ResourceManager.GetString("ToCurrencyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        internal static string TradeHeader {
            get {
                return ResourceManager.GetString("TradeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume (USD).
        /// </summary>
        internal static string VolumeHeader {
            get {
                return ResourceManager.GetString("VolumeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume (USD): {0:C0}.
        /// </summary>
        internal static string VolumeLabelFormat {
            get {
                return ResourceManager.GetString("VolumeLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string VolumeMarketHeader {
            get {
                return ResourceManager.GetString("VolumeMarketHeader", resourceCulture);
            }
        }
    }
}
